### ISSUE TITLE
bug: ModuleNotFoundError: No module named 'hausdorff.distances'; 'hausdorff' is not a package

### ISSUE THREAD

**Issue by Questdream** [mavillan/py-hausdorff#10]
Traceback (most recent call last):
  File "D:/coding/py-hausdorff-master/hausdorff/hausdorff.py", line 3, in <module>
    import hausdorff.distances as distances
  File "D:\coding\py-hausdorff-master\hausdorff\hausdorff.py", line 3, in <module>
    import hausdorff.distances as distances
ModuleNotFoundError: No module named 'hausdorff.distances'; 'hausdorff' is not a package
#when i try to run code ,the mistake happended as above, how should i do to fix it ? i have installed all package as instruction.

**Comment by mavillan** [comment]
Hi! How do you installed the package, using pip or with setup.py?

**Comment by Jiaxin-lim** [comment]
Hi, i know you have closed this but there is still bug regarding this issue even after pip installation of hausdorff

**Comment by jiayily** [comment]
@Jiaxin-lim Have you solved this problem? Can you share your method? Thank you
