### ISSUE TITLE
Type()-checking for np.ndarray is overly restrictive to subclasses

### ISSUE THREAD

**Issue by sbetko** [mavillan/py-hausdorff#15]
**Problem:** In `hausdorff.hausdorff_distance`, the first assertion, that `type(XA) is np.ndarray and type(XB) is np.ndarray`, is overly restrictive as it disallows sub-classes of `numpy.ndarray`. For example, a common use-case is to call this function on the points of a PyVista mesh, which are stored in a [`pyvista.pyvista_ndarray`](https://github.com/pyvista/pyvista/blob/c91015ee837708ff008c5d917c27714b0f6082db/pyvista/core/pyvista_ndarray.py#L11). This object subclasses from `numpy.ndarray` and is functionally identical but this function raises an assertion error if an instance is passed in.

https://github.com/mavillan/py-hausdorff/blob/cf13865ef4307c68508bccccf44c38661e45dc56/hausdorff/hausdorff.py#L39-L40

**Steps to reproduce:** Create a subclass of `numpy.ndarray` and pass an instance into `hausdorff.hausdorff_distance`.
```python
import numpy as np
from hausdorff import hausdorff_distance

class my_ndarray(np.ndarray): pass
a = my_ndarray(np.array([5, 2]))
hausdorff_distance(a, a) # raises AssertionError
```

**Comment by sbetko** [comment]
I made a pull request to fix this issue. See #16.

**Comment by mavillan** [comment]
Already merged it, thanks for contributing!
