### ISSUE TITLE
implementation using cosine distance

### ISSUE THREAD

**Issue by Manas0706** [mavillan/py-hausdorff#2]
Hi Mavillan,
I am not able to find any way to use cosine distance while implementing this package. Please guide.

Regards,
Manas

**Comment by mavillan** [comment]
Hi @Manas0706 

In its current form it is not possible to use the cosine distance in a straightforward way. I will review the changes needed to improve the current interface, so that it can receive custom distance functions. 

Regards,
-- Mavillan

**Comment by mavillan** [comment]
Hi @Manas0706 

The cosine distance is now available to use. I hope it's still useful to you.
